In [1]:
import pandas as pd
import unicodedata
import re
import os

# 1. Cargar los datos
BASE_DIR = "."

ruta_rend = os.path.join(BASE_DIR, "rendimiento_municipios_2007_2024.csv")
ruta_clima = os.path.join(BASE_DIR, "clima_anual_municipio.csv")
ruta_altitud = os.path.join(BASE_DIR, "altitud_municipios.csv")

df_rendimientos = pd.read_csv(ruta_rend)
df_clima = pd.read_csv(ruta_clima)
df_altitud = pd.read_csv(ruta_altitud)

In [2]:
df_rendimientos.head()

,Año,Departamento,Municipio,Producto,Área Cosechada,Área Sembrada,Producción,Rendimiento,Ciclo
0,2013,ANTIOQUIA,ABEJORRAL,CAFE,3050.02,3713.32,1717.46,0.563098,PERMANENTE
1,2012,ANTIOQUIA,ABEJORRAL,CAFE,3000.00,3701.00,2398.12,0.799373,PERMANENTE
2,2011,ANTIOQUIA,ABEJORRAL,CAFE,3290.00,3959.00,1500.00,0.455927,PERMANENTE
3,2010,ANTIOQUIA,ABEJORRAL,CAFE,3665.00,4052.00,2528.90,0.690014,PERMANENTE
4,2008,ANTIOQUIA,ABEJORRAL,CAFE,3956.00,4180.00,2223.30,0.562007,PERMANENTE

In [3]:
df_rendimientos.columns = df_rendimientos.columns.str.strip().str.lower()

In [4]:
df_clima.head()

,departamento,municipio,cod_mpio,anio,Precipitación acumulada anual (mm/año),Temperatura media anual (°C),Máximo de la temperatura media mensual (°C),Mínimo de la temperatura media mensual (°C),Humedad relativa media anual (%),Radiación solar acumulada anual (MJ/m²/año),...,SPI12_mean_anual,SPI12_min_anual,SPI12_meses_bajo_m1,SPI3_dic,SPI6_dic,SPI12_dic,SPI1_floracion,SPI3_floracion,SPI1_llenado,SPI3_llenado
0,AMAZONAS,EL ENCANTO,263,2007,2666.462670,25.049417,27.371168,23.914051,91.788510,6006.697223,...,-0.891624,-0.891624,0,0.176009,-0.667193,-0.891624,NaN,NaN,NaN,NaN
1,AMAZONAS,EL ENCANTO,263,2008,2603.152147,24.953180,25.650776,23.982166,91.714080,6095.789341,...,-0.829704,-1.164608,1,-0.347264,-0.967635,-1.164608,NaN,NaN,NaN,NaN
2,AMAZONAS,EL ENCANTO,263,2009,3103.099748,24.999098,25.744907,24.137667,93.223816,5851.208812,...,0.643977,-0.477887,0,-0.317426,-0.985042,0.882195,NaN,NaN,NaN,NaN
3,AMAZONAS,EL ENCANTO,263,2010,2630.808462,25.457466,26.198406,24.427956,92.433655,6100.684080,...,-0.581413,-1.044816,1,-0.529588,-1.808670,-1.044816,NaN,NaN,NaN,NaN
4,AMAZONAS,EL ENCANTO,263,2011,2884.234096,24.960299,25.541845,24.213293,92.633300,5840.694218,...,-0.694557,-1.139250,2,0.069561,-0.845803,0.015468,NaN,NaN,NaN,NaN

In [5]:
df_altitud.head()

,system:index,altitud_max_m,altitud_media_m,altitud_mediana_m,altitud_min_m,cod_mpio,departamento,municipio,.geo
0,0000000000000000043f,98,23.154799,11.000000,-6,1,"ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANT...",SAN ANDRÉS,"{""type"":""MultiPoint"",""coordinates"":[]}"
1,0000000000000000043e,357,84.015961,62.528689,-1,564,"ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANT...",PROVIDENCIA,"{""type"":""MultiPoint"",""coordinates"":[]}"
2,00000000000000000094,4155,3221.287842,3287.515686,192,1,"BOGOTÁ, D.C.","BOGOTÁ, D.C.","{""type"":""MultiPoint"",""coordinates"":[]}"
3,00000000000000000453,642,208.615143,201.551279,108,1,GUAVIARE,SAN JOSÉ DEL GUAVIARE,"{""type"":""MultiPoint"",""coordinates"":[]}"
4,00000000000000000454,818,268.845989,257.559988,177,15,GUAVIARE,CALAMAR,"{""type"":""MultiPoint"",""coordinates"":[]}"

In [6]:
df_rendimientos = df_rendimientos.rename(columns={"año": "anio"})
df_rendimientos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10972 entries, 0 to 10971
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   anio            10972 non-null  int64
 1   departamento    10972 non-null  object
 2   municipio       10972 non-null  object
 3   producto        10972 non-null  object
 4   área cosechada  10972 non-null  float64
 5   área sembrada   10972 non-null  float64
 6   producción      10972 non-null  float64
 7   rendimiento     10972 non-null  float64
 8   ciclo           10972 non-null  object
dtypes: float64(4), int64(1), object(4)
memory usage: 771.6+ KB

In [7]:
df_clima.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18090 entries, 0 to 18089
Data columns (total 29 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   departamento                                              18090 non-null  object
 1   municipio                                                 18090 non-null  object
 2   cod_mpio                                                  18090 non-null  int64
 3   anio                                                      18090 non-null  int64
 4   Precipitación acumulada anual (mm/año)                    18090 non-null  float64
 5   Temperatura media anual (°C)                              18090 non-null  float64
 6   Máximo de la temperatura media mensual (°C)               18090 non-null  float64
 7   Mínimo de la temperatura media mensual (°C)               18090 non-null  float64
 8   Humedad relativa media anual (%)                          18090 non-null  float64
 9   Radiación solar acumulada anual (MJ/m²/año)               18090 non-null  float64
 10  Humedad volumétrica media anual del suelo capa 1 (m³/m³)  18090 non-null  float64
 11  Humedad volumétrica media anual del suelo capa 2 (m³/m³)  18090 non-null  float64
 12  Evaporación potencial acumulada anual (mm/año)            18090 non-null  float64
 13  SPI3_mean_anual                                           18090 non-null  float64
 14  SPI3_min_anual                                            18090 non-null  float64
 15  SPI3_meses_bajo_m1                                        18090 non-null  int64
 16  SPI6_mean_anual                                           18090 non-null  float64
 17  SPI6_min_anual                                            18090 non-null  float64
 18  SPI6_meses_bajo_m1                                        18090 non-null  int64
 19  SPI12_mean_anual                                          18090 non-null  float64
 20  SPI12_min_anual                                           18090 non-null  float64
 21  SPI12_meses_bajo_m1                                       18090 non-null  int64
 22  SPI3_dic                                                  18090 non-null  float64
 23  SPI6_dic                                                  18090 non-null  float64
 24  SPI12_dic                                                 18090 non-null  float64
 25  SPI1_floracion                                            2610 non-null   float64
 26  SPI3_floracion                                            2610 non-null   float64
 27  SPI1_llenado                                              2610 non-null   float64
 28  SPI3_llenado                                              2610 non-null   float64
dtypes: float64(22), int64(5), object(2)
memory usage: 4.0+ MB

In [8]:
df_altitud.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1121 entries, 0 to 1120
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   system:index       1121 non-null   object
 1   altitud_max_m      1121 non-null   int64
 2   altitud_media_m    1121 non-null   float64
 3   altitud_mediana_m  1121 non-null   float64
 4   altitud_min_m      1121 non-null   int64
 5   cod_mpio           1121 non-null   int64
 6   departamento       1121 non-null   object
 7   municipio          1121 non-null   object
 8   .geo               1121 non-null   object
dtypes: float64(2), int64(3), object(4)
memory usage: 78.9+ KB

In [9]:
# Estandarizar texto
df_clima["departamento"] = (
    df_clima["departamento"]
    .astype(str)
    .str.strip()
    .str.upper()
)

# Filtrar solo CUNDINAMARCA y NARIÑO
df_clima = df_clima[
    df_clima["departamento"].isin(["CUNDINAMARCA", "NARIÑO"])
].copy()

# Validar
df_clima["departamento"].value_counts()

departamento
CUNDINAMARCA    1692
NARIÑO           918
Name: count, dtype: int64

In [10]:
# Estandarizar texto
df_altitud["departamento"] = (
    df_altitud["departamento"]
    .astype(str)
    .str.strip()
    .str.upper()
)

# Filtrar solo CUNDINAMARCA y NARIÑO
df_altitud = df_altitud[
    df_altitud["departamento"].isin(["CUNDINAMARCA", "NARIÑO"])
].copy()

# Validar
df_altitud["departamento"].value_counts()

departamento
CUNDINAMARCA    116
NARIÑO           64
Name: count, dtype: int64

In [11]:
# Estandarizar texto
df_rendimientos["departamento"] = (
    df_rendimientos["departamento"]
    .astype(str)
    .str.strip()
    .str.upper()
)

# Filtrar solo CUNDINAMARCA y NARIÑO
df_rendimientos = df_rendimientos[
    df_rendimientos["departamento"].isin(["CUNDINAMARCA", "NARIÑO"])
].copy()

# Validar
df_rendimientos["departamento"].value_counts()

departamento
CUNDINAMARCA    1232
NARIÑO           708
Name: count, dtype: int64

In [12]:
df_clima.head()

,departamento,municipio,cod_mpio,anio,Precipitación acumulada anual (mm/año),Temperatura media anual (°C),Máximo de la temperatura media mensual (°C),Mínimo de la temperatura media mensual (°C),Humedad relativa media anual (%),Radiación solar acumulada anual (MJ/m²/año),...,SPI12_mean_anual,SPI12_min_anual,SPI12_meses_bajo_m1,SPI3_dic,SPI6_dic,SPI12_dic,SPI1_floracion,SPI3_floracion,SPI1_llenado,SPI3_llenado
7992,CUNDINAMARCA,ANAPOIMA,35,2007,9637.491363,21.440603,23.470367,20.613922,82.14768,5434.224617,...,1.182698,1.182698,0,-0.477296,-0.110409,1.182698,-0.224038,0.063614,0.337495,0.368694
7993,CUNDINAMARCA,ANAPOIMA,35,2008,9397.211458,21.052603,21.534576,20.717682,83.73498,5434.937062,...,0.994708,0.302250,0,-0.660129,0.442474,0.990945,0.034885,0.288161,-0.041813,0.090587
7994,CUNDINAMARCA,ANAPOIMA,35,2009,7596.002594,21.659576,22.564850,21.122711,82.47872,5691.733904,...,0.445177,-0.561965,0,-1.038473,-0.650928,-0.561965,-0.147636,-0.076189,-0.367224,-0.240564
7995,CUNDINAMARCA,ANAPOIMA,35,2010,10091.935886,21.505259,23.381012,19.950592,84.22712,5287.102522,...,0.144954,-1.176374,3,-0.475811,0.739385,1.536935,0.060390,0.094568,0.601869,0.299247
7996,CUNDINAMARCA,ANAPOIMA,35,2011,8696.465524,21.023651,21.647125,20.361969,85.47486,5323.956911,...,1.115979,0.383516,0,-0.484511,-0.099035,0.412532,0.015540,0.021867,0.398428,0.166396

In [13]:
def resumen_general_df(nombre_df, df):
    filas, columnas = df.shape
    
    duplicados = df.duplicated().sum()
    
    total_nulos = df.isna().sum().sum()
    
    # Cuenta celdas vacías tipo "", "   " solo en columnas object/string
    total_vacios = (
        df.select_dtypes(include=["object", "string"])
        .apply(lambda col: col.astype(str).str.strip().eq("").sum())
        .sum()
    )
    
    columnas_con_nulos = df.columns[df.isna().any()].tolist()
    
    columnas_con_vacios = []
    for col in df.select_dtypes(include=["object", "string"]).columns:
        if df[col].astype(str).str.strip().eq("").any():
            columnas_con_vacios.append(col)
    
    return pd.DataFrame({
        "DataFrame": [nombre_df],
        "Filas": [filas],
        "Columnas": [columnas],
        "Duplicados": [duplicados],
        "Total nulos": [total_nulos],
        "Total vacíos": [total_vacios],
        "Columnas con nulos": [", ".join(columnas_con_nulos) if columnas_con_nulos else "Ninguna"],
        "Columnas con vacíos": [", ".join(columnas_con_vacios) if columnas_con_vacios else "Ninguna"]
    })

In [14]:
dfs = {
    "df_rendimientos": df_rendimientos,
    "df_clima": df_clima,
    "df_altitud": df_altitud
}
resumen_general = pd.concat(
    [resumen_general_df(nombre, df) for nombre, df in dfs.items()],
    ignore_index=True
)

resumen_general

,DataFrame,Filas,Columnas,Duplicados,Total nulos,Total vacíos,Columnas con nulos,Columnas con vacíos
0,df_rendimientos,1940,9,0,0,0,Ninguna,Ninguna
1,df_clima,2610,29,0,0,0,Ninguna,Ninguna
2,df_altitud,180,9,0,0,0,Ninguna,Ninguna

In [15]:
import pandas as pd
import numpy as np
import unicodedata

# Llaves para el merge
keys = ["departamento", "anio", "municipio"]

In [16]:
def limpiar_texto(x):
    if pd.isna(x):
        return np.nan
    
    x = str(x).strip().upper()
    
    # Quitar tildes
    x = ''.join(
        c for c in unicodedata.normalize('NFD', x)
        if unicodedata.category(c) != 'Mn'
    )
    
    return x

In [17]:
rend = df_rendimientos.copy()
clima = df_clima.copy()

# Limpiar columnas de texto usadas como llave
for df in [rend, clima]:
    df["departamento"] = df["departamento"].apply(limpiar_texto)
    df["municipio"] = df["municipio"].apply(limpiar_texto)
    df["anio"] = pd.to_numeric(df["anio"], errors="coerce")

In [18]:
rend = rend.dropna(subset=keys)
clima = clima.dropna(subset=keys)

In [19]:
rend = rend.drop_duplicates()
clima = clima.drop_duplicates()

In [20]:
sin_clima = rend.merge(
    clima[keys].drop_duplicates(),
    on=keys,
    how="left",
    indicator=True
)

sin_clima = sin_clima[sin_clima["_merge"] == "left_only"]

municipios_sin_clima = sin_clima[keys].drop_duplicates().sort_values(
    by=["departamento", "municipio", "anio"]
)

municipios_sin_clima

      departamento  anio     municipio
2     CUNDINAMARCA  2007  AGUA DE DIOS
3     CUNDINAMARCA  2008  AGUA DE DIOS
5     CUNDINAMARCA  2009  AGUA DE DIOS
0     CUNDINAMARCA  2010  AGUA DE DIOS
1     CUNDINAMARCA  2013  AGUA DE DIOS
...            ...   ...           ...
1915        NARINO  2020    YACUANQUER
1918        NARINO  2021    YACUANQUER
1917        NARINO  2022    YACUANQUER
1908        NARINO  2023    YACUANQUER
1916        NARINO  2024    YACUANQUER

[345 rows x 3 columns]

In [21]:
resumen_sin_clima = (
    municipios_sin_clima
    .groupby(["departamento", "municipio"])
    .agg(
        anios_sin_clima=("anio", lambda x: sorted(x.unique())),
        cantidad_anios_sin_clima=("anio", "nunique")
    )
    .reset_index()
    .sort_values(by=["departamento", "municipio"])
)

resumen_sin_clima

,departamento,municipio,anios_sin_clima,cantidad_anios_sin_clima
0,CUNDINAMARCA,AGUA DE DIOS,"[2007, 2008, 2009, 2010, 2013, 2019, 2021]",7
1,CUNDINAMARCA,ALBAN,"[2007, 2008, 2009, 2010, 2011, 2012, 2013, 201...",17
2,CUNDINAMARCA,BITUIMA,"[2007, 2008, 2009, 2010, 2011, 2012, 2013, 201...",18
3,CUNDINAMARCA,LA VEGA,"[2007, 2008, 2009, 2010, 2011, 2012, 2013, 201...",18
4,CUNDINAMARCA,MANTA,"[2007, 2008, 2009, 2010, 2011, 2012, 2013, 201...",18
5,CUNDINAMARCA,NIMAIMA,"[2007, 2008, 2009, 2010, 2011, 2012, 2013, 201...",18
6,CUNDINAMARCA,QUIPILE,"[2007, 2008, 2009, 2010, 2011, 2012, 2013, 201...",18
7,CUNDINAMARCA,SAN ANTONIO DEL TEQUENDAMA,"[2007, 2008, 2009, 2010, 2011, 2012, 2013, 201...",18
8,CUNDINAMARCA,TENA,"[2007, 2008, 2009, 2010, 2011, 2012, 2013, 201...",18
9,CUNDINAMARCA,TOPAIPI,"[2007, 2008, 2009, 2010, 2011, 2012, 2013, 201...",18
10,CUNDINAMARCA,VENECIA,"[2007, 2008, 2009, 2010, 2011, 2012, 2013, 201...",18
11,CUNDINAMARCA,VIANI,"[2007, 2008, 2009, 2010, 2011, 2012, 2013, 201...",18
12,NARINO,ALBAN,"[2007, 2008, 2009, 2010, 2011, 2012, 2013, 201...",18
13,NARINO,ANCUYA,"[2007, 2008, 2009, 2010, 2011, 2012, 2013, 201...",18
14,NARINO,BELEN,"[2007, 2008, 2009, 2010, 2011, 2012, 2023, 2024]",8
15,NARINO,COLON,"[2007, 2008, 2009, 2010, 2011, 2012, 2013, 201...",18
16,NARINO,EL TABLON,"[2007, 2008, 2009, 2010, 2011, 2012, 2013, 201...",18
17,NARINO,NARINO,"[2007, 2008, 2009, 2010, 2011, 2012]",6
18,NARINO,SAN BERNARDO,"[2007, 2008, 2009, 2010, 2011, 2012, 2013, 201...",18
19,NARINO,SAN PEDRO DE CARTAGO,"[2007, 2008, 2009, 2010, 2011, 2012, 2013, 201...",18
20,NARINO,TUMACO,[2011],1
21,NARINO,YACUANQUER,"[2007, 2008, 2009, 2010, 2011, 2012, 2013, 201...",18

In [22]:
df_rend_clima = rend.merge(
    clima,
    on=keys,
    how="inner",
    suffixes=("_rend", "_clima")
)
print("Tamaño df_rendimientos original:", df_rendimientos.shape)
print("Tamaño df_clima original:", df_clima.shape)
print("Tamaño base final rendimiento + clima:", df_rend_clima.shape)

df_rend_clima.head()

Tamaño df_rendimientos original: (1940, 9)
Tamaño df_clima original: (2610, 29)
Tamaño base final rendimiento + clima: (1595, 35)

,anio,departamento,municipio,producto,área cosechada,área sembrada,producción,rendimiento,ciclo,cod_mpio,...,SPI12_mean_anual,SPI12_min_anual,SPI12_meses_bajo_m1,SPI3_dic,SPI6_dic,SPI12_dic,SPI1_floracion,SPI3_floracion,SPI1_llenado,SPI3_llenado
0,2011,CUNDINAMARCA,ANAPOIMA,CAFE,245.00,247.00,116.0000,0.473469,PERMANENTE,35,...,1.115979,0.383516,0,-0.484511,-0.099035,0.412532,0.015540,0.021867,0.398428,0.166396
1,2012,CUNDINAMARCA,ANAPOIMA,CAFE,107.00,107.00,53.5000,0.500000,PERMANENTE,35,...,0.113505,-0.330545,0,-0.608266,-0.362650,-0.330545,-0.069946,-0.136889,-0.022393,0.012682
2,2010,CUNDINAMARCA,ANAPOIMA,CAFE,244.25,251.16,114.1000,0.467144,PERMANENTE,35,...,0.144954,-1.176374,3,-0.475811,0.739385,1.536935,0.060390,0.094568,0.601869,0.299247
3,2013,CUNDINAMARCA,ANAPOIMA,CAFE,129.38,138.04,58.0749,0.448871,PERMANENTE,35,...,-0.023286,-0.598976,0,-0.512001,0.256218,0.563384,0.371155,0.088846,0.162142,0.133923
4,2024,CUNDINAMARCA,ANAPOIMA,CAFE,44.52,51.39,67.2200,1.509883,PERMANENTE,35,...,-0.103992,-1.389557,2,-0.171846,0.096995,0.717714,-0.756288,-0.413278,0.411031,0.394549

In [23]:
duplicados_final = df_rend_clima.duplicated(subset=keys).sum()

print("Duplicados por departamento, anio y municipio en base final:", duplicados_final)

Duplicados por departamento, anio y municipio en base final: 0

In [24]:
keys_altitud = ["departamento", "municipio"]

In [25]:
rend_clima = df_rend_clima.copy()
altitud = df_altitud.copy()

for df in [rend_clima, altitud]:
    df["departamento"] = df["departamento"].apply(limpiar_texto)
    df["municipio"] = df["municipio"].apply(limpiar_texto)

In [26]:
rend_clima = rend_clima.dropna(subset=keys_altitud)
altitud = altitud.dropna(subset=keys_altitud)

In [27]:
rend_clima = rend_clima.drop_duplicates()
altitud = altitud.drop_duplicates()

In [28]:
columnas_numericas_altitud = altitud.select_dtypes(include=["number"]).columns.tolist()
columnas_categoricas_altitud = altitud.select_dtypes(exclude=["number"]).columns.tolist()

columnas_numericas_altitud = [
    col for col in columnas_numericas_altitud 
    if col not in keys_altitud
]

columnas_categoricas_altitud = [
    col for col in columnas_categoricas_altitud 
    if col not in keys_altitud
]

agg_altitud = {}

for col in columnas_numericas_altitud:
    agg_altitud[col] = "mean"

for col in columnas_categoricas_altitud:
    agg_altitud[col] = "first"

altitud = altitud.groupby(keys_altitud, as_index=False).agg(agg_altitud)

In [29]:
sin_altitud = rend_clima.merge(
    altitud[keys_altitud].drop_duplicates(),
    on=keys_altitud,
    how="left",
    indicator=True
)

sin_altitud = sin_altitud[sin_altitud["_merge"] == "left_only"]

municipios_sin_altitud = (
    sin_altitud[keys_altitud]
    .drop_duplicates()
    .sort_values(by=["departamento", "municipio"])
)

municipios_sin_altitud

Empty DataFrame
Columns: [departamento, municipio]
Index: []

In [30]:
df_final = rend_clima.merge(
    altitud,
    on=keys_altitud,
    how="inner",
    suffixes=("", "_altitud")
)

In [31]:
df_final = df_final.dropna()

In [32]:
print("Tamaño df_rend_clima:", df_rend_clima.shape)
print("Tamaño df_altitud:", df_altitud.shape)
print("Tamaño df_final:", df_final.shape)

df_final.head()

Tamaño df_rend_clima: (1595, 35)
Tamaño df_altitud: (180, 9)
Tamaño df_final: (1595, 42)

,anio,departamento,municipio,producto,área cosechada,área sembrada,producción,rendimiento,ciclo,cod_mpio,...,SPI3_floracion,SPI1_llenado,SPI3_llenado,altitud_max_m,altitud_media_m,altitud_mediana_m,altitud_min_m,cod_mpio_altitud,system:index,.geo
0,2011,CUNDINAMARCA,ANAPOIMA,CAFE,245.00,247.00,116.0000,0.473469,PERMANENTE,35,...,0.021867,0.398428,0.166396,1569.0,753.137185,723.552443,449.0,35.0,000000000000000001cb,"{""type"":""MultiPoint"",""coordinates"":[]}"
1,2012,CUNDINAMARCA,ANAPOIMA,CAFE,107.00,107.00,53.5000,0.500000,PERMANENTE,35,...,-0.136889,-0.022393,0.012682,1569.0,753.137185,723.552443,449.0,35.0,000000000000000001cb,"{""type"":""MultiPoint"",""coordinates"":[]}"
2,2010,CUNDINAMARCA,ANAPOIMA,CAFE,244.25,251.16,114.1000,0.467144,PERMANENTE,35,...,0.094568,0.601869,0.299247,1569.0,753.137185,723.552443,449.0,35.0,000000000000000001cb,"{""type"":""MultiPoint"",""coordinates"":[]}"
3,2013,CUNDINAMARCA,ANAPOIMA,CAFE,129.38,138.04,58.0749,0.448871,PERMANENTE,35,...,0.088846,0.162142,0.133923,1569.0,753.137185,723.552443,449.0,35.0,000000000000000001cb,"{""type"":""MultiPoint"",""coordinates"":[]}"
4,2024,CUNDINAMARCA,ANAPOIMA,CAFE,44.52,51.39,67.2200,1.509883,PERMANENTE,35,...,-0.413278,0.411031,0.394549,1569.0,753.137185,723.552443,449.0,35.0,000000000000000001cb,"{""type"":""MultiPoint"",""coordinates"":[]}"

In [33]:
duplicados_final = df_final.duplicated(
    subset=["departamento", "municipio", "anio"]
).sum()

print("Duplicados finales por departamento, municipio y año:", duplicados_final)

Duplicados finales por departamento, municipio y año: 0

In [34]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1595 entries, 0 to 1594
Data columns (total 42 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   anio                                                      1595 non-null   int64
 1   departamento                                              1595 non-null   object
 2   municipio                                                 1595 non-null   object
 3   producto                                                  1595 non-null   object
 4   área cosechada                                            1595 non-null   float64
 5   área sembrada                                             1595 non-null   float64
 6   producción                                                1595 non-null   float64
 7   rendimiento                                               1595 non-null   float64
 8   ciclo                                                     1595 non-null   object
 9   cod_mpio                                                  1595 non-null   int64
 10  Precipitación acumulada anual (mm/año)                    1595 non-null   float64
 11  Temperatura media anual (°C)                              1595 non-null   float64
 12  Máximo de la temperatura media mensual (°C)               1595 non-null   float64
 13  Mínimo de la temperatura media mensual (°C)               1595 non-null   float64
 14  Humedad relativa media anual (%)                          1595 non-null   float64
 15  Radiación solar acumulada anual (MJ/m²/año)               1595 non-null   float64
 16  Humedad volumétrica media anual del suelo capa 1 (m³/m³)  1595 non-null   float64
 17  Humedad volumétrica media anual del suelo capa 2 (m³/m³)  1595 non-null   float64
 18  Evaporación potencial acumulada anual (mm/año)            1595 non-null   float64
 19  SPI3_mean_anual                                           1595 non-null   float64
 20  SPI3_min_anual                                            1595 non-null   float64
 21  SPI3_meses_bajo_m1                                        1595 non-null   int64
 22  SPI6_mean_anual                                           1595 non-null   float64
 23  SPI6_min_anual                                            1595 non-null   float64
 24  SPI6_meses_bajo_m1                                        1595 non-null   int64
 25  SPI12_mean_anual                                          1595 non-null   float64
 26  SPI12_min_anual                                           1595 non-null   float64
 27  SPI12_meses_bajo_m1                                       1595 non-null   int64
 28  SPI3_dic                                                  1595 non-null   float64
 29  SPI6_dic                                                  1595 non-null   float64
 30  SPI12_dic                                                 1595 non-null   float64
 31  SPI1_floracion                                            1595 non-null   float64
 32  SPI3_floracion                                            1595 non-null   float64
 33  SPI1_llenado                                              1595 non-null   float64
 34  SPI3_llenado                                              1595 non-null   float64
 35  altitud_max_m                                             1595 non-null   float64
 36  altitud_media_m                                           1595 non-null   float64
 37  altitud_mediana_m                                         1595 non-null   float64
 38  altitud_min_m                                             1595 non-null   float64
 39  cod_mpio_altitud                                          1595 non-null   float64
 40  system:index                                              1595 non-null   object
 41  .geo                                                      1595 non-null   object
dtypes: float64(31), int64(5), object(6)
memory usage: 523.5+ KB

In [35]:
# Asegurar que no haya espacios raros en nombres de columnas
df_final.columns = df_final.columns.str.strip()

# Target
target = "rendimiento"

# Columnas que no deberían entrar como variables explicativas
columnas_eliminar = [
    "Unnamed: 0",              # índice exportado desde CSV
    "producto",                # no aporta si todo es café
    "ciclo",                   # categoría administrativa / no climática
    "system:index",            # índice de Google Earth Engine u origen similar
    ".geo",                    # geometría cruda, no variable numérica directa

    # Llaves creadas para cruces / joins
    "departamento_key_rend",
    "municipio_key_rend",
    "anio_key_rend",
    "departamento_key_clima",
    "municipio_key_clima",
    "anio_key_clima",

    # Código duplicado creado en cruce con altitud
    "cod_mpio_altitud"
]

# Eliminar solo las columnas que existan en el df
df_final = df_final.drop(
    columns=[c for c in columnas_eliminar if c in df_final.columns]
)

# Verificar resultado
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1595 entries, 0 to 1594
Data columns (total 37 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   anio                                                      1595 non-null   int64
 1   departamento                                              1595 non-null   object
 2   municipio                                                 1595 non-null   object
 3   área cosechada                                            1595 non-null   float64
 4   área sembrada                                             1595 non-null   float64
 5   producción                                                1595 non-null   float64
 6   rendimiento                                               1595 non-null   float64
 7   cod_mpio                                                  1595 non-null   int64
 8   Precipitación acumulada anual (mm/año)                    1595 non-null   float64
 9   Temperatura media anual (°C)                              1595 non-null   float64
 10  Máximo de la temperatura media mensual (°C)               1595 non-null   float64
 11  Mínimo de la temperatura media mensual (°C)               1595 non-null   float64
 12  Humedad relativa media anual (%)                          1595 non-null   float64
 13  Radiación solar acumulada anual (MJ/m²/año)               1595 non-null   float64
 14  Humedad volumétrica media anual del suelo capa 1 (m³/m³)  1595 non-null   float64
 15  Humedad volumétrica media anual del suelo capa 2 (m³/m³)  1595 non-null   float64
 16  Evaporación potencial acumulada anual (mm/año)            1595 non-null   float64
 17  SPI3_mean_anual                                           1595 non-null   float64
 18  SPI3_min_anual                                            1595 non-null   float64
 19  SPI3_meses_bajo_m1                                        1595 non-null   int64
 20  SPI6_mean_anual                                           1595 non-null   float64
 21  SPI6_min_anual                                            1595 non-null   float64
 22  SPI6_meses_bajo_m1                                        1595 non-null   int64
 23  SPI12_mean_anual                                          1595 non-null   float64
 24  SPI12_min_anual                                           1595 non-null   float64
 25  SPI12_meses_bajo_m1                                       1595 non-null   int64
 26  SPI3_dic                                                  1595 non-null   float64
 27  SPI6_dic                                                  1595 non-null   float64
 28  SPI12_dic                                                 1595 non-null   float64
 29  SPI1_floracion                                            1595 non-null   float64
 30  SPI3_floracion                                            1595 non-null   float64
 31  SPI1_llenado                                              1595 non-null   float64
 32  SPI3_llenado                                              1595 non-null   float64
 33  altitud_max_m                                             1595 non-null   float64
 34  altitud_media_m                                           1595 non-null   float64
 35  altitud_mediana_m                                         1595 non-null   float64
 36  altitud_min_m                                             1595 non-null   float64
dtypes: float64(30), int64(5), object(2)
memory usage: 461.2+ KB

In [36]:
columnas_fuga = [
    "producción",
    "área cosechada"
]

df_final = df_final.drop(
    columns=[c for c in columnas_fuga if c in df_final.columns]
)

In [37]:
# Mantener rendimiento y altitud media
# Eliminar altitudes menos representativas
columnas_eliminar = [
    "altitud_min_m",
    "altitud_max_m",
    "altitud_mediana_m",
    "cod_mpio_altitud",
    "cod_mpio"
]

df_final = df_final.drop(
    columns=[c for c in columnas_eliminar if c in df_final.columns]
)

df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1595 entries, 0 to 1594
Data columns (total 31 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   anio                                                      1595 non-null   int64
 1   departamento                                              1595 non-null   object
 2   municipio                                                 1595 non-null   object
 3   área sembrada                                             1595 non-null   float64
 4   rendimiento                                               1595 non-null   float64
 5   Precipitación acumulada anual (mm/año)                    1595 non-null   float64
 6   Temperatura media anual (°C)                              1595 non-null   float64
 7   Máximo de la temperatura media mensual (°C)               1595 non-null   float64
 8   Mínimo de la temperatura media mensual (°C)               1595 non-null   float64
 9   Humedad relativa media anual (%)                          1595 non-null   float64
 10  Radiación solar acumulada anual (MJ/m²/año)               1595 non-null   float64
 11  Humedad volumétrica media anual del suelo capa 1 (m³/m³)  1595 non-null   float64
 12  Humedad volumétrica media anual del suelo capa 2 (m³/m³)  1595 non-null   float64
 13  Evaporación potencial acumulada anual (mm/año)            1595 non-null   float64
 14  SPI3_mean_anual                                           1595 non-null   float64
 15  SPI3_min_anual                                            1595 non-null   float64
 16  SPI3_meses_bajo_m1                                        1595 non-null   int64
 17  SPI6_mean_anual                                           1595 non-null   float64
 18  SPI6_min_anual                                            1595 non-null   float64
 19  SPI6_meses_bajo_m1                                        1595 non-null   int64
 20  SPI12_mean_anual                                          1595 non-null   float64
 21  SPI12_min_anual                                           1595 non-null   float64
 22  SPI12_meses_bajo_m1                                       1595 non-null   int64
 23  SPI3_dic                                                  1595 non-null   float64
 24  SPI6_dic                                                  1595 non-null   float64
 25  SPI12_dic                                                 1595 non-null   float64
 26  SPI1_floracion                                            1595 non-null   float64
 27  SPI3_floracion                                            1595 non-null   float64
 28  SPI1_llenado                                              1595 non-null   float64
 29  SPI3_llenado                                              1595 non-null   float64
 30  altitud_media_m                                           1595 non-null   float64
dtypes: float64(25), int64(4), object(2)
memory usage: 386.4+ KB

In [38]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [39]:
# =========================
# 1. Copia de trabajo
# =========================

df_fe = df_final.copy()
df_fe.columns = df_fe.columns.str.strip().str.lower()

target = "rendimiento"

# Separar target
y = df_fe[target].copy()

In [40]:
# 2. Variables categóricas
# =========================

df_fe["anio"] = df_fe["anio"].astype("Int64").astype(str).astype("category")
df_fe["departamento"] = df_fe["departamento"].astype("category")
df_fe["municipio"] = df_fe["municipio"].astype("category")

In [41]:
df_fe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1595 entries, 0 to 1594
Data columns (total 31 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   anio                                                      1595 non-null   category
 1   departamento                                              1595 non-null   category
 2   municipio                                                 1595 non-null   category
 3   área sembrada                                             1595 non-null   float64
 4   rendimiento                                               1595 non-null   float64
 5   precipitación acumulada anual (mm/año)                    1595 non-null   float64
 6   temperatura media anual (°c)                              1595 non-null   float64
 7   máximo de la temperatura media mensual (°c)               1595 non-null   float64
 8   mínimo de la temperatura media mensual (°c)               1595 non-null   float64
 9   humedad relativa media anual (%)                          1595 non-null   float64
 10  radiación solar acumulada anual (mj/m²/año)               1595 non-null   float64
 11  humedad volumétrica media anual del suelo capa 1 (m³/m³)  1595 non-null   float64
 12  humedad volumétrica media anual del suelo capa 2 (m³/m³)  1595 non-null   float64
 13  evaporación potencial acumulada anual (mm/año)            1595 non-null   float64
 14  spi3_mean_anual                                           1595 non-null   float64
 15  spi3_min_anual                                            1595 non-null   float64
 16  spi3_meses_bajo_m1                                        1595 non-null   int64
 17  spi6_mean_anual                                           1595 non-null   float64
 18  spi6_min_anual                                            1595 non-null   float64
 19  spi6_meses_bajo_m1                                        1595 non-null   int64
 20  spi12_mean_anual                                          1595 non-null   float64
 21  spi12_min_anual                                           1595 non-null   float64
 22  spi12_meses_bajo_m1                                       1595 non-null   int64
 23  spi3_dic                                                  1595 non-null   float64
 24  spi6_dic                                                  1595 non-null   float64
 25  spi12_dic                                                 1595 non-null   float64
 26  spi1_floracion                                            1595 non-null   float64
 27  spi3_floracion                                            1595 non-null   float64
 28  spi1_llenado                                              1595 non-null   float64
 29  spi3_llenado                                              1595 non-null   float64
 30  altitud_media_m                                           1595 non-null   float64
dtypes: category(3), float64(25), int64(3)
memory usage: 357.3 KB

In [42]:
# =========================
# 3. Feature engineering térmico
# =========================

df_fe["amplitud_temperatura_media_mensual"] = (
    df_fe["máximo de la temperatura media mensual (°c)"]
    - df_fe["mínimo de la temperatura media mensual (°c)"]
)

# =========================
# 4. Feature engineering hídrico
# =========================

df_fe["balance_precipitacion_evaporacion"] = (
    df_fe["precipitación acumulada anual (mm/año)"]
    - df_fe["evaporación potencial acumulada anual (mm/año)"]
)

df_fe["ratio_precipitacion_evaporacion"] = (
    df_fe["precipitación acumulada anual (mm/año)"]
    / (df_fe["evaporación potencial acumulada anual (mm/año)"] + 1e-6)
)

# Transformaciones logarítmicas para acumulados positivos
cols_log = [
    "área sembrada",
    "precipitación acumulada anual (mm/año)",
    "radiación solar acumulada anual (mj/m²/año)",
    "evaporación potencial acumulada anual (mm/año)"
]

for col in cols_log:
    if col in df_fe.columns:
        df_fe[f"log1p_{col}"] = np.log1p(df_fe[col])

# =========================
# 5. Humedad del suelo
# =========================

capa1 = "humedad volumétrica media anual del suelo capa 1 (m³/m³)"
capa2 = "humedad volumétrica media anual del suelo capa 2 (m³/m³)"

df_fe["humedad_suelo_promedio_capas_1_2"] = (
    df_fe[capa1] + df_fe[capa2]
) / 2

df_fe["humedad_suelo_diferencia_capa2_capa1"] = (
    df_fe[capa2] - df_fe[capa1]
)

# =========================
# 6. SPI: intensidad y duración de sequía
# =========================

for escala in [3, 6, 12]:
    col_min = f"spi{escala}_min_anual"
    col_meses = f"spi{escala}_meses_bajo_m1"

    df_fe[f"spi{escala}_deficit_max_anual"] = np.maximum(
        0,
        -df_fe[col_min]
    )

    df_fe[f"spi{escala}_presion_sequia_anual"] = (
        df_fe[f"spi{escala}_deficit_max_anual"] * df_fe[col_meses]
    )

df_fe["spi_presion_total_sequia"] = (
    df_fe["spi3_presion_sequia_anual"]
    + df_fe["spi6_presion_sequia_anual"]
    + df_fe["spi12_presion_sequia_anual"]
)

df_fe["spi_promedio_dic"] = (
    df_fe["spi3_dic"] + df_fe["spi6_dic"] + df_fe["spi12_dic"]
) / 3

df_fe["spi1_cambio_llenado_vs_floracion"] = (
    df_fe["spi1_llenado"] - df_fe["spi1_floracion"]
)

df_fe["spi3_cambio_llenado_vs_floracion"] = (
    df_fe["spi3_llenado"] - df_fe["spi3_floracion"]
)

In [78]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [79]:
TARGET = "rendimiento"

# Variables numéricas predictoras, excluyendo target
variables_numericas_modelo = [
    col for col in df_fe.select_dtypes(include=[np.number]).columns
    if col != TARGET
]

X_num = df_fe[variables_numericas_modelo].copy()

# Estandarizar
scaler = StandardScaler()
Z = scaler.fit_transform(X_num)

# PCA sin target
pca = PCA()
scores = pca.fit_transform(Z)

componentes = [f"PC{i}" for i in range(1, len(variables_numericas_modelo) + 1)]

loadings = pca.components_.T * np.sqrt(pca.explained_variance_)

loadings_df = pd.DataFrame(
    loadings,
    index=variables_numericas_modelo,
    columns=componentes
)

pca_resumen = pd.DataFrame({
    "componente": componentes,
    "autovalor": pca.explained_variance_,
    "varianza_explicada": pca.explained_variance_ratio_,
    "varianza_acumulada": np.cumsum(pca.explained_variance_ratio_)
})

pca_resumen.head(15)

   componente  autovalor  varianza_explicada  varianza_acumulada
0         PC1  15.603904            0.339003            0.339003
1         PC2   6.545491            0.142204            0.481207
2         PC3   5.455819            0.118530            0.599737
3         PC4   4.111377            0.089322            0.689059
4         PC5   3.055524            0.066383            0.755442
5         PC6   2.033626            0.044182            0.799623
6         PC7   1.541425            0.033488            0.833111
7         PC8   1.373684            0.029844            0.862955
8         PC9   0.952073            0.020684            0.883640
9        PC10   0.791888            0.017204            0.900844
10       PC11   0.669090            0.014536            0.915380
11       PC12   0.623719            0.013551            0.928931
12       PC13   0.512552            0.011135            0.940066
13       PC14   0.416241            0.009043            0.949109
14       PC15   0.337872            0.007340            0.956450

In [80]:
# Usar componentes que expliquen mínimo 80% de la varianza
umbral_varianza = 0.90

n_componentes = np.argmax(
    pca_resumen["varianza_acumulada"] >= umbral_varianza
) + 1

pcs_usar = [f"PC{i}" for i in range(1, n_componentes + 1)]

# Score PCA: carga absoluta promedio en los componentes importantes
pca_importancia = pd.DataFrame({
    "variable": loadings_df.index,
    "score_pca": loadings_df[pcs_usar].abs().mean(axis=1),
    "max_loading_abs": loadings_df[pcs_usar].abs().max(axis=1)
}).sort_values("score_pca", ascending=False)

pca_importancia.head(20)

,variable,score_pca,max_loading_abs
spi1_cambio_llenado_vs_floracion,spi1_cambio_llenado_vs_floracion,0.271280,0.497197
log1p_evaporación potencial acumulada anual (mm/año),log1p_evaporación potencial acumulada anual (m...,0.245750,0.551179
spi1_llenado,spi1_llenado,0.243697,0.682030
evaporación potencial acumulada anual (mm/año),evaporación potencial acumulada anual (mm/año),0.238211,0.589032
spi12_presion_sequia_anual,spi12_presion_sequia_anual,0.236518,0.722057
spi12_meses_bajo_m1,spi12_meses_bajo_m1,0.228074,0.728203
spi3_dic,spi3_dic,0.224269,0.602080
spi3_cambio_llenado_vs_floracion,spi3_cambio_llenado_vs_floracion,0.223383,0.660287
spi1_floracion,spi1_floracion,0.220980,0.673916
log1p_precipitación acumulada anual (mm/año),log1p_precipitación acumulada anual (mm/año),0.220927,0.782819
máximo de la temperatura media mensual (°c),máximo de la temperatura media mensual (°c),0.219690,0.723267
temperatura media anual (°c),temperatura media anual (°c),0.219392,0.718580
mínimo de la temperatura media mensual (°c),mínimo de la temperatura media mensual (°c),0.215638,0.710440
humedad volumétrica media anual del suelo capa 1 (m³/m³),humedad volumétrica media anual del suelo capa...,0.215363,0.805740
log1p_radiación solar acumulada anual (mj/m²/año),log1p_radiación solar acumulada anual (mj/m²/año),0.215123,0.527351
spi12_dic,spi12_dic,0.215056,0.790163
spi3_llenado,spi3_llenado,0.214052,0.614881
radiación solar acumulada anual (mj/m²/año),radiación solar acumulada anual (mj/m²/año),0.213638,0.518444
spi_promedio_dic,spi_promedio_dic,0.213195,0.665186
spi3_floracion,spi3_floracion,0.212392,0.716770

In [81]:
corr_target = []

for col in variables_numericas_modelo:
    pearson = df_fe[[col, TARGET]].corr(method="pearson").iloc[0, 1]
    spearman = df_fe[[col, TARGET]].corr(method="spearman").iloc[0, 1]
    
    corr_target.append({
        "variable": col,
        "pearson_r_target": pearson,
        "spearman_r_target": spearman,
        "abs_pearson_target": abs(pearson),
        "abs_spearman_target": abs(spearman),
        "score_corr_target": max(abs(pearson), abs(spearman))
    })

corr_target_df = pd.DataFrame(corr_target).sort_values(
    "score_corr_target",
    ascending=False
)

corr_target_df.head(20)

,variable,pearson_r_target,spearman_r_target,abs_pearson_target,abs_spearman_target,score_corr_target
6,radiación solar acumulada anual (mj/m²/año),0.130149,0.281075,0.130149,0.281075,0.281075
32,log1p_radiación solar acumulada anual (mj/m²/año),0.128663,0.281075,0.128663,0.281075,0.281075
45,spi3_cambio_llenado_vs_floracion,0.048751,0.261146,0.048751,0.261146,0.261146
23,spi3_floracion,-0.005232,-0.196348,0.005232,0.196348,0.196348
19,spi3_dic,0.072929,0.179266,0.072929,0.179266,0.179266
18,spi12_meses_bajo_m1,0.067593,0.178098,0.067593,0.178098,0.178098
41,spi12_presion_sequia_anual,0.056724,0.171351,0.056724,0.171351,0.171351
37,spi3_presion_sequia_anual,0.044737,0.165862,0.044737,0.165862,0.165862
42,spi_presion_total_sequia,0.049702,0.165415,0.049702,0.165415,0.165415
12,spi3_meses_bajo_m1,0.047933,0.162101,0.047933,0.162101,0.162101
28,balance_precipitacion_evaporacion,-0.043692,-0.153717,0.043692,0.153717,0.153717
29,ratio_precipitacion_evaporacion,-0.034018,-0.149594,0.034018,0.149594,0.149594
0,área sembrada,0.065303,0.148452,0.065303,0.148452,0.148452
30,log1p_área sembrada,0.095381,0.148452,0.095381,0.148452,0.148452
1,precipitación acumulada anual (mm/año),-0.046397,-0.146028,0.046397,0.146028,0.146028
31,log1p_precipitación acumulada anual (mm/año),-0.039710,-0.146028,0.039710,0.146028,0.146028
36,spi3_deficit_max_anual,0.010193,0.139453,0.010193,0.139453,0.139453
11,spi3_min_anual,-0.010004,-0.139442,0.010004,0.139442,0.139442
16,spi12_mean_anual,0.003189,-0.137624,0.003189,0.137624,0.137624
15,spi6_meses_bajo_m1,0.024819,0.135300,0.024819,0.135300,0.135300

In [82]:
def calcular_vif(X):
    X_temp = X.copy()
    X_temp = X_temp.replace([np.inf, -np.inf], np.nan)
    X_temp = X_temp.fillna(X_temp.median())

    X_const = sm.add_constant(X_temp, has_constant="add")

    resultados = []

    for i, col in enumerate(X_const.columns):
        if col == "const":
            continue

        vif = variance_inflation_factor(X_const.values, i)

        resultados.append({
            "variable": col,
            "VIF": vif
        })

    return pd.DataFrame(resultados).sort_values("VIF", ascending=False)


vif_df = calcular_vif(X_num)

vif_df.head(30)

C:\Users\ramires7\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

                                             variable          VIF
1              precipitación acumulada anual (mm/año)          inf
3         máximo de la temperatura media mensual (°c)          inf
4         mínimo de la temperatura media mensual (°c)          inf
9      evaporación potencial acumulada anual (mm/año)          inf
8   humedad volumétrica media anual del suelo capa...          inf
7   humedad volumétrica media anual del suelo capa...          inf
22                                     spi1_floracion          inf
23                                     spi3_floracion          inf
24                                       spi1_llenado          inf
25                                       spi3_llenado          inf
27                 amplitud_temperatura_media_mensual          inf
19                                           spi3_dic          inf
21                                          spi12_dic          inf
20                                           spi6_dic          inf
45                   spi3_cambio_llenado_vs_floracion          inf
39                          spi6_presion_sequia_anual          inf
43                                   spi_promedio_dic          inf
42                           spi_presion_total_sequia          inf
44                   spi1_cambio_llenado_vs_floracion          inf
34                   humedad_suelo_promedio_capas_1_2          inf
37                          spi3_presion_sequia_anual          inf
35               humedad_suelo_diferencia_capa2_capa1          inf
28                  balance_precipitacion_evaporacion          inf
41                         spi12_presion_sequia_anual          inf
36                             spi3_deficit_max_anual  8077.590997
11                                     spi3_min_anual  8061.932088
2                        temperatura media anual (°c)   571.552469
6         radiación solar acumulada anual (mj/m²/año)   542.668780
32  log1p_radiación solar acumulada anual (mj/m²/año)   537.051293
14                                     spi6_min_anual   134.442512

In [83]:
resumen_metricas = (
    corr_target_df
    .merge(pca_importancia, on="variable", how="left")
    .merge(vif_df, on="variable", how="left")
)

resumen_metricas["VIF_limpio"] = resumen_metricas["VIF"].replace(np.inf, 1e9)

resumen_metricas.sort_values("VIF_limpio", ascending=False).head(30)

,variable,pearson_r_target,spearman_r_target,abs_pearson_target,abs_spearman_target,score_corr_target,score_pca,max_loading_abs,VIF,VIF_limpio
3,spi3_floracion,-0.005232,-0.196348,0.005232,0.196348,0.196348,0.212392,0.716770,inf,1.000000e+09
2,spi3_cambio_llenado_vs_floracion,0.048751,0.261146,0.048751,0.261146,0.261146,0.223383,0.660287,inf,1.000000e+09
4,spi3_dic,0.072929,0.179266,0.072929,0.179266,0.179266,0.224269,0.602080,inf,1.000000e+09
8,spi_presion_total_sequia,0.049702,0.165415,0.049702,0.165415,0.165415,0.195708,0.877671,inf,1.000000e+09
7,spi3_presion_sequia_anual,0.044737,0.165862,0.044737,0.165862,0.165862,0.177406,0.866374,inf,1.000000e+09
6,spi12_presion_sequia_anual,0.056724,0.171351,0.056724,0.171351,0.171351,0.236518,0.722057,inf,1.000000e+09
10,balance_precipitacion_evaporacion,-0.043692,-0.153717,0.043692,0.153717,0.153717,0.195703,0.804495,inf,1.000000e+09
40,mínimo de la temperatura media mensual (°c),0.025772,-0.034250,0.025772,0.034250,0.034250,0.215638,0.710440,inf,1.000000e+09
44,humedad volumétrica media anual del suelo capa...,0.024276,-0.015162,0.024276,0.015162,0.024276,0.209697,0.810932,inf,1.000000e+09
29,evaporación potencial acumulada anual (mm/año),0.019496,0.104910,0.019496,0.104910,0.104910,0.238211,0.589032,inf,1.000000e+09
22,spi3_llenado,0.061971,0.123135,0.061971,0.123135,0.123135,0.214052,0.614881,inf,1.000000e+09
25,spi1_floracion,-0.001911,-0.109892,0.001911,0.109892,0.109892,0.220980,0.673916,inf,1.000000e+09
20,spi6_presion_sequia_anual,0.026480,0.131501,0.026480,0.131501,0.131501,0.187387,0.863182,inf,1.000000e+09
14,precipitación acumulada anual (mm/año),-0.046397,-0.146028,0.046397,0.146028,0.146028,0.211473,0.815509,inf,1.000000e+09
43,humedad_suelo_promedio_capas_1_2,0.026720,-0.009609,0.026720,0.009609,0.026720,0.211342,0.809741,inf,1.000000e+09
37,spi1_llenado,0.007576,0.045152,0.007576,0.045152,0.045152,0.243697,0.682030,inf,1.000000e+09
35,spi_promedio_dic,0.071060,0.016021,0.071060,0.016021,0.071060,0.213195,0.665186,inf,1.000000e+09
36,spi6_dic,0.064834,-0.045700,0.064834,0.045700,0.064834,0.196009,0.614499,inf,1.000000e+09
34,spi12_dic,0.047256,-0.080164,0.047256,0.080164,0.080164,0.215056,0.790163,inf,1.000000e+09
33,amplitud_temperatura_media_mensual,-0.006719,0.090044,0.006719,0.090044,0.090044,0.204985,0.512793,inf,1.000000e+09
32,humedad_suelo_diferencia_capa2_capa1,-0.028914,-0.091844,0.028914,0.091844,0.091844,0.210194,0.361747,inf,1.000000e+09
45,máximo de la temperatura media mensual (°c),0.021651,-0.016647,0.021651,0.016647,0.021651,0.219690,0.723267,inf,1.000000e+09
41,humedad volumétrica media anual del suelo capa...,0.029196,-0.003394,0.029196,0.003394,0.029196,0.215363,0.805740,inf,1.000000e+09
31,spi1_cambio_llenado_vs_floracion,0.008624,0.104406,0.008624,0.104406,0.104406,0.271280,0.497197,inf,1.000000e+09
16,spi3_deficit_max_anual,0.010193,0.139453,0.010193,0.139453,0.139453,0.181024,0.826137,8077.590997,8.077591e+03
17,spi3_min_anual,-0.010004,-0.139442,0.010004,0.139442,0.139442,0.180929,0.826076,8061.932088,8.061932e+03
42,temperatura media anual (°c),0.027108,-0.024321,0.027108,0.024321,0.027108,0.219392,0.718580,571.552469,5.715525e+02
0,radiación solar acumulada anual (mj/m²/año),0.130149,0.281075,0.130149,0.281075,0.281075,0.213638,0.518444,542.668780,5.426688e+02
1,log1p_radiación solar acumulada anual (mj/m²/año),0.128663,0.281075,0.128663,0.281075,0.281075,0.215123,0.527351,537.051293,5.370513e+02
27,spi6_min_anual,-0.002261,-0.105254,0.002261,0.105254,0.105254,0.173594,0.872410,134.442512,1.344425e+02

In [84]:
grupos_redundantes = [
    {
        "grupo": "area_log",
        "variables": [
            "área sembrada",
            "log1p_área sembrada"
        ],
        "max_keep": 1
    },
    {
        "grupo": "precipitacion_evaporacion",
        "variables": [
            "precipitación acumulada anual (mm/año)",
            "evaporación potencial acumulada anual (mm/año)",
            "balance_precipitacion_evaporacion",
            "ratio_precipitacion_evaporacion",
            "log1p_precipitación acumulada anual (mm/año)",
            "log1p_evaporación potencial acumulada anual (mm/año)"
        ],
        "max_keep": 2
    },
    {
        "grupo": "radiacion_log",
        "variables": [
            "radiación solar acumulada anual (mj/m²/año)",
            "log1p_radiación solar acumulada anual (mj/m²/año)"
        ],
        "max_keep": 1
    },
    {
        "grupo": "temperatura",
        "variables": [
            "temperatura media anual (°c)",
            "máximo de la temperatura media mensual (°c)",
            "mínimo de la temperatura media mensual (°c)",
            "amplitud_temperatura_media_mensual"
        ],
        "max_keep": 2
    },
    {
        "grupo": "humedad_suelo",
        "variables": [
            "humedad volumétrica media anual del suelo capa 1 (m³/m³)",
            "humedad volumétrica media anual del suelo capa 2 (m³/m³)",
            "humedad_suelo_promedio_capas_1_2",
            "humedad_suelo_diferencia_capa2_capa1"
        ],
        "max_keep": 2
    },
    {
        "grupo": "spi_dic",
        "variables": [
            "spi3_dic",
            "spi6_dic",
            "spi12_dic",
            "spi_promedio_dic"
        ],
        "max_keep": 2
    },
    {
        "grupo": "spi1_fases",
        "variables": [
            "spi1_floracion",
            "spi1_llenado",
            "spi1_cambio_llenado_vs_floracion"
        ],
        "max_keep": 2
    },
    {
        "grupo": "spi3_fases",
        "variables": [
            "spi3_floracion",
            "spi3_llenado",
            "spi3_cambio_llenado_vs_floracion"
        ],
        "max_keep": 2
    },
    {
        "grupo": "spi3_sequia",
        "variables": [
            "spi3_min_anual",
            "spi3_deficit_max_anual",
            "spi3_meses_bajo_m1",
            "spi3_presion_sequia_anual"
        ],
        "max_keep": 2
    },
    {
        "grupo": "spi6_sequia",
        "variables": [
            "spi6_min_anual",
            "spi6_deficit_max_anual",
            "spi6_meses_bajo_m1",
            "spi6_presion_sequia_anual"
        ],
        "max_keep": 2
    },
    {
        "grupo": "spi12_sequia",
        "variables": [
            "spi12_min_anual",
            "spi12_deficit_max_anual",
            "spi12_meses_bajo_m1",
            "spi12_presion_sequia_anual"
        ],
        "max_keep": 2
    },
    {
        "grupo": "spi_presion_total",
        "variables": [
            "spi3_presion_sequia_anual",
            "spi6_presion_sequia_anual",
            "spi12_presion_sequia_anual",
            "spi_presion_total_sequia"
        ],
        "max_keep": 2
    }
]

In [85]:
def seleccionar_variables_por_grupo(resumen_metricas, grupos_redundantes):
    eliminadas = []
    mantenidas = []

    for grupo in grupos_redundantes:
        nombre_grupo = grupo["grupo"]
        variables = [v for v in grupo["variables"] if v in resumen_metricas["variable"].values]
        max_keep = grupo["max_keep"]

        if len(variables) <= max_keep:
            continue

        temp = resumen_metricas[resumen_metricas["variable"].isin(variables)].copy()

        # Mejor variable:
        # 1. mayor correlación con target
        # 2. mayor importancia PCA
        # 3. menor VIF
        temp = temp.sort_values(
            by=["score_corr_target", "score_pca", "VIF_limpio"],
            ascending=[False, False, True]
        )

        vars_keep = temp.head(max_keep)["variable"].tolist()
        vars_drop = temp.iloc[max_keep:]["variable"].tolist()

        for v in vars_keep:
            mantenidas.append({
                "grupo": nombre_grupo,
                "variable": v,
                "decision": "mantener"
            })

        for v in vars_drop:
            eliminadas.append({
                "grupo": nombre_grupo,
                "variable": v,
                "decision": "eliminar",
                "razon": "Redundante dentro del grupo; menor correlación con target, menor PCA o mayor VIF"
            })

    return pd.DataFrame(mantenidas), pd.DataFrame(eliminadas)


mantenidas_grupos, eliminadas_grupos = seleccionar_variables_por_grupo(
    resumen_metricas,
    grupos_redundantes
)

eliminadas_grupos

,grupo,variable,decision,razon
0,area_log,área sembrada,eliminar,Redundante dentro del grupo; menor correlación...
1,precipitacion_evaporacion,log1p_precipitación acumulada anual (mm/año),eliminar,Redundante dentro del grupo; menor correlación...
2,precipitacion_evaporacion,precipitación acumulada anual (mm/año),eliminar,Redundante dentro del grupo; menor correlación...
3,precipitacion_evaporacion,log1p_evaporación potencial acumulada anual (m...,eliminar,Redundante dentro del grupo; menor correlación...
4,precipitacion_evaporacion,evaporación potencial acumulada anual (mm/año),eliminar,Redundante dentro del grupo; menor correlación...
5,radiacion_log,radiación solar acumulada anual (mj/m²/año),eliminar,Redundante dentro del grupo; menor correlación...
6,temperatura,temperatura media anual (°c),eliminar,Redundante dentro del grupo; menor correlación...
7,temperatura,máximo de la temperatura media mensual (°c),eliminar,Redundante dentro del grupo; menor correlación...
8,humedad_suelo,humedad_suelo_promedio_capas_1_2,eliminar,Redundante dentro del grupo; menor correlación...
9,humedad_suelo,humedad volumétrica media anual del suelo capa...,eliminar,Redundante dentro del grupo; menor correlación...
10,spi_dic,spi_promedio_dic,eliminar,Redundante dentro del grupo; menor correlación...
11,spi_dic,spi6_dic,eliminar,Redundante dentro del grupo; menor correlación...
12,spi1_fases,spi1_llenado,eliminar,Redundante dentro del grupo; menor correlación...
13,spi3_fases,spi3_llenado,eliminar,Redundante dentro del grupo; menor correlación...
14,spi3_sequia,spi3_deficit_max_anual,eliminar,Redundante dentro del grupo; menor correlación...
15,spi3_sequia,spi3_min_anual,eliminar,Redundante dentro del grupo; menor correlación...
16,spi6_sequia,spi6_min_anual,eliminar,Redundante dentro del grupo; menor correlación...
17,spi6_sequia,spi6_deficit_max_anual,eliminar,Redundante dentro del grupo; menor correlación...
18,spi12_sequia,spi12_min_anual,eliminar,Redundante dentro del grupo; menor correlación...
19,spi12_sequia,spi12_deficit_max_anual,eliminar,Redundante dentro del grupo; menor correlación...
20,spi_presion_total,spi_presion_total_sequia,eliminar,Redundante dentro del grupo; menor correlación...
21,spi_presion_total,spi6_presion_sequia_anual,eliminar,Redundante dentro del grupo; menor correlación...

In [86]:
def pares_altamente_correlacionados(corr_matrix, umbral=0.85):
    pares = []

    cols = corr_matrix.columns

    for i in range(len(cols)):
        for j in range(i + 1, len(cols)):
            r = corr_matrix.iloc[i, j]

            if abs(r) >= umbral:
                pares.append({
                    "variable_1": cols[i],
                    "variable_2": cols[j],
                    "correlacion": r,
                    "abs_correlacion": abs(r)
                })

    return pd.DataFrame(pares).sort_values("abs_correlacion", ascending=False)


corr_predictoras = X_num.corr(method="pearson")

pares_corr_alta = pares_altamente_correlacionados(
    corr_predictoras,
    umbral=0.85
)

pares_corr_alta.head(30)

,variable_1,variable_2,correlacion,abs_correlacion
16,spi3_min_anual,spi3_deficit_max_anual,-0.999917,0.999917
12,humedad volumétrica media anual del suelo capa...,humedad_suelo_promedio_capas_1_2,0.998422,0.998422
9,radiación solar acumulada anual (mj/m²/año),log1p_radiación solar acumulada anual (mj/m²/año),0.998325,0.998325
11,humedad volumétrica media anual del suelo capa...,humedad_suelo_promedio_capas_1_2,0.998260,0.998260
4,temperatura media anual (°c),mínimo de la temperatura media mensual (°c),0.995534,0.995534
3,temperatura media anual (°c),máximo de la temperatura media mensual (°c),0.993718,0.993718
10,humedad volumétrica media anual del suelo capa...,humedad volumétrica media anual del suelo capa...,0.993373,0.993373
21,spi6_min_anual,spi6_deficit_max_anual,-0.992721,0.992721
6,máximo de la temperatura media mensual (°c),mínimo de la temperatura media mensual (°c),0.983166,0.983166
14,spi3_mean_anual,spi6_mean_anual,0.968520,0.968520
0,precipitación acumulada anual (mm/año),balance_precipitacion_evaporacion,0.959058,0.959058
28,spi12_meses_bajo_m1,spi12_presion_sequia_anual,0.957838,0.957838
27,spi12_min_anual,spi12_deficit_max_anual,-0.957672,0.957672
13,evaporación potencial acumulada anual (mm/año),log1p_evaporación potencial acumulada anual (m...,0.957209,0.957209
1,precipitación acumulada anual (mm/año),ratio_precipitacion_evaporacion,0.952319,0.952319
23,spi6_meses_bajo_m1,spi6_presion_sequia_anual,0.950222,0.950222
8,mínimo de la temperatura media mensual (°c),altitud_media_m,-0.947859,0.947859
5,temperatura media anual (°c),altitud_media_m,-0.947161,0.947161
2,precipitación acumulada anual (mm/año),log1p_precipitación acumulada anual (mm/año),0.939302,0.939302
18,spi3_meses_bajo_m1,spi3_presion_sequia_anual,0.939078,0.939078
33,balance_precipitacion_evaporacion,ratio_precipitacion_evaporacion,0.938523,0.938523
34,balance_precipitacion_evaporacion,log1p_precipitación acumulada anual (mm/año),0.938201,0.938201
7,máximo de la temperatura media mensual (°c),altitud_media_m,-0.935389,0.935389
15,spi3_mean_anual,spi12_dic,0.934586,0.934586
40,spi6_presion_sequia_anual,spi_presion_total_sequia,0.927471,0.927471
25,spi12_mean_anual,spi12_min_anual,0.920873,0.920873
42,spi12_presion_sequia_anual,spi_presion_total_sequia,0.919150,0.919150
19,spi6_mean_anual,spi12_mean_anual,0.909937,0.909937
31,spi6_dic,spi_promedio_dic,0.909612,0.909612
30,spi3_dic,spi3_llenado,0.900784,0.900784

In [87]:
def decidir_eliminar_por_pares(pares_corr_alta, resumen_metricas, variables_ya_eliminadas=None):
    if variables_ya_eliminadas is None:
        variables_ya_eliminadas = set()

    eliminadas = []

    metricas = resumen_metricas.set_index("variable")

    for _, row in pares_corr_alta.iterrows():
        v1 = row["variable_1"]
        v2 = row["variable_2"]

        if v1 in variables_ya_eliminadas or v2 in variables_ya_eliminadas:
            continue

        if v1 not in metricas.index or v2 not in metricas.index:
            continue

        m1 = metricas.loc[v1]
        m2 = metricas.loc[v2]

        # Regla:
        # eliminar la que tenga menor correlación con target.
        # si empatan, eliminar mayor VIF.
        # si empatan, eliminar menor PCA.
        score1 = (
            m1["score_corr_target"],
            m1["score_pca"],
            -m1["VIF_limpio"]
        )

        score2 = (
            m2["score_corr_target"],
            m2["score_pca"],
            -m2["VIF_limpio"]
        )

        if score1 >= score2:
            eliminar = v2
            mantener = v1
        else:
            eliminar = v1
            mantener = v2

        variables_ya_eliminadas.add(eliminar)

        eliminadas.append({
            "variable_eliminada": eliminar,
            "variable_mantenida": mantener,
            "correlacion": row["correlacion"],
            "abs_correlacion": row["abs_correlacion"],
            "razon": "Alta correlación entre predictoras"
        })

    return pd.DataFrame(eliminadas)


variables_eliminadas_iniciales = set(eliminadas_grupos["variable"].tolist())

eliminadas_corr = decidir_eliminar_por_pares(
    pares_corr_alta,
    resumen_metricas,
    variables_ya_eliminadas=variables_eliminadas_iniciales
)

eliminadas_corr.head(30)

,variable_eliminada,variable_mantenida,correlacion,abs_correlacion,razon
0,spi3_mean_anual,spi6_mean_anual,0.968520,0.968520,Alta correlación entre predictoras
1,spi12_presion_sequia_anual,spi12_meses_bajo_m1,0.957838,0.957838,Alta correlación entre predictoras
2,mínimo de la temperatura media mensual (°c),altitud_media_m,-0.947859,0.947859,Alta correlación entre predictoras
3,spi3_meses_bajo_m1,spi3_presion_sequia_anual,0.939078,0.939078,Alta correlación entre predictoras
4,ratio_precipitacion_evaporacion,balance_precipitacion_evaporacion,0.938523,0.938523,Alta correlación entre predictoras
5,spi6_mean_anual,spi12_mean_anual,0.909937,0.909937,Alta correlación entre predictoras

In [88]:
def reducir_vif_iterativo(X, resumen_metricas, variables_excluir=None, umbral_vif=10):
    if variables_excluir is None:
        variables_excluir = set()

    variables_actuales = [
        col for col in X.columns
        if col not in variables_excluir
    ]

    historial = []

    while True:
        vif_actual = calcular_vif(X[variables_actuales])
        vif_actual["VIF_limpio"] = vif_actual["VIF"].replace(np.inf, 1e9)

        max_vif = vif_actual["VIF_limpio"].max()

        if max_vif <= umbral_vif or len(variables_actuales) <= 2:
            break

        candidatas = vif_actual[vif_actual["VIF_limpio"] > umbral_vif].copy()

        temp = candidatas.merge(
            resumen_metricas[["variable", "score_corr_target", "score_pca"]],
            on="variable",
            how="left"
        )

        # Eliminar la peor:
        # menor relación con target,
        # menor importancia PCA,
        # mayor VIF
        temp = temp.sort_values(
            by=["score_corr_target", "score_pca", "VIF_limpio"],
            ascending=[True, True, False]
        )

        var_eliminar = temp.iloc[0]["variable"]

        historial.append({
            "variable_eliminada": var_eliminar,
            "VIF": temp.iloc[0]["VIF"],
            "score_corr_target": temp.iloc[0]["score_corr_target"],
            "score_pca": temp.iloc[0]["score_pca"],
            "razon": f"VIF mayor a {umbral_vif}"
        })

        variables_actuales.remove(var_eliminar)

    vif_final = calcular_vif(X[variables_actuales])

    return variables_actuales, pd.DataFrame(historial), vif_final


variables_excluir = set(eliminadas_grupos["variable"].tolist()) | set(eliminadas_corr["variable_eliminada"].tolist())

variables_finales_lineal, eliminadas_vif, vif_final = reducir_vif_iterativo(
    X=X_num,
    resumen_metricas=resumen_metricas,
    variables_excluir=variables_excluir,
    umbral_vif=10
)

eliminadas_vif

  variable_eliminada        VIF  score_corr_target  score_pca           razon
0     spi3_floracion  16.754051           0.196348   0.212392  VIF mayor a 10

In [89]:
variables_a_eliminar = sorted(
    set(eliminadas_grupos["variable"].tolist())
    | set(eliminadas_corr["variable_eliminada"].tolist())
    | set(eliminadas_vif["variable_eliminada"].tolist())
)

variables_a_usar_lineal = [
    col for col in variables_numericas_modelo
    if col not in variables_a_eliminar
]

print("======================================")
print("VARIABLES A ELIMINAR")
print("======================================")
for v in variables_a_eliminar:
    print("-", v)

print("\n======================================")
print("VARIABLES A USAR EN MODELO LINEAL")
print("======================================")
for v in variables_a_usar_lineal:
    print("-", v)

print("\nTotal eliminadas:", len(variables_a_eliminar))
print("Total usadas:", len(variables_a_usar_lineal))

======================================
VARIABLES A ELIMINAR
======================================
- evaporación potencial acumulada anual (mm/año)
- humedad volumétrica media anual del suelo capa 2 (m³/m³)
- humedad_suelo_promedio_capas_1_2
- log1p_evaporación potencial acumulada anual (mm/año)
- log1p_precipitación acumulada anual (mm/año)
- máximo de la temperatura media mensual (°c)
- mínimo de la temperatura media mensual (°c)
- precipitación acumulada anual (mm/año)
- radiación solar acumulada anual (mj/m²/año)
- ratio_precipitacion_evaporacion
- spi12_deficit_max_anual
- spi12_min_anual
- spi12_presion_sequia_anual
- spi1_llenado
- spi3_deficit_max_anual
- spi3_floracion
- spi3_llenado
- spi3_mean_anual
- spi3_meses_bajo_m1
- spi3_min_anual
- spi6_deficit_max_anual
- spi6_dic
- spi6_mean_anual
- spi6_min_anual
- spi6_presion_sequia_anual
- spi_presion_total_sequia
- spi_promedio_dic
- temperatura media anual (°c)
- área sembrada

======================================
VARIABLES A USAR EN MODELO LINEAL
======================================
- humedad relativa media anual (%)
- humedad volumétrica media anual del suelo capa 1 (m³/m³)
- spi6_meses_bajo_m1
- spi12_mean_anual
- spi12_meses_bajo_m1
- spi3_dic
- spi12_dic
- spi1_floracion
- altitud_media_m
- amplitud_temperatura_media_mensual
- balance_precipitacion_evaporacion
- log1p_área sembrada
- log1p_radiación solar acumulada anual (mj/m²/año)
- humedad_suelo_diferencia_capa2_capa1
- spi3_presion_sequia_anual
- spi1_cambio_llenado_vs_floracion
- spi3_cambio_llenado_vs_floracion

Total eliminadas: 29
Total usadas: 17

In [90]:
tabla_eliminadas_1 = eliminadas_grupos.rename(
    columns={"variable": "variable_eliminada"}
)[["variable_eliminada", "razon", "grupo"]]

tabla_eliminadas_2 = eliminadas_corr[[
    "variable_eliminada",
    "razon",
    "variable_mantenida",
    "correlacion"
]]

tabla_eliminadas_3 = eliminadas_vif[[
    "variable_eliminada",
    "razon",
    "VIF",
    "score_corr_target",
    "score_pca"
]]

resumen_eliminacion = pd.concat(
    [
        tabla_eliminadas_1,
        tabla_eliminadas_2,
        tabla_eliminadas_3
    ],
    ignore_index=True,
    sort=False
)

resumen_eliminacion = resumen_eliminacion.drop_duplicates(
    subset=["variable_eliminada"],
    keep="first"
)

resumen_eliminacion

,variable_eliminada,razon,grupo,variable_mantenida,correlacion,VIF,score_corr_target,score_pca
0,área sembrada,Redundante dentro del grupo; menor correlación...,area_log,NaN,NaN,NaN,NaN,NaN
1,log1p_precipitación acumulada anual (mm/año),Redundante dentro del grupo; menor correlación...,precipitacion_evaporacion,NaN,NaN,NaN,NaN,NaN
2,precipitación acumulada anual (mm/año),Redundante dentro del grupo; menor correlación...,precipitacion_evaporacion,NaN,NaN,NaN,NaN,NaN
3,log1p_evaporación potencial acumulada anual (m...,Redundante dentro del grupo; menor correlación...,precipitacion_evaporacion,NaN,NaN,NaN,NaN,NaN
4,evaporación potencial acumulada anual (mm/año),Redundante dentro del grupo; menor correlación...,precipitacion_evaporacion,NaN,NaN,NaN,NaN,NaN
5,radiación solar acumulada anual (mj/m²/año),Redundante dentro del grupo; menor correlación...,radiacion_log,NaN,NaN,NaN,NaN,NaN
6,temperatura media anual (°c),Redundante dentro del grupo; menor correlación...,temperatura,NaN,NaN,NaN,NaN,NaN
7,máximo de la temperatura media mensual (°c),Redundante dentro del grupo; menor correlación...,temperatura,NaN,NaN,NaN,NaN,NaN
8,humedad_suelo_promedio_capas_1_2,Redundante dentro del grupo; menor correlación...,humedad_suelo,NaN,NaN,NaN,NaN,NaN
9,humedad volumétrica media anual del suelo capa...,Redundante dentro del grupo; menor correlación...,humedad_suelo,NaN,NaN,NaN,NaN,NaN
10,spi_promedio_dic,Redundante dentro del grupo; menor correlación...,spi_dic,NaN,NaN,NaN,NaN,NaN
11,spi6_dic,Redundante dentro del grupo; menor correlación...,spi_dic,NaN,NaN,NaN,NaN,NaN
12,spi1_llenado,Redundante dentro del grupo; menor correlación...,spi1_fases,NaN,NaN,NaN,NaN,NaN
13,spi3_llenado,Redundante dentro del grupo; menor correlación...,spi3_fases,NaN,NaN,NaN,NaN,NaN
14,spi3_deficit_max_anual,Redundante dentro del grupo; menor correlación...,spi3_sequia,NaN,NaN,NaN,NaN,NaN
15,spi3_min_anual,Redundante dentro del grupo; menor correlación...,spi3_sequia,NaN,NaN,NaN,NaN,NaN
16,spi6_min_anual,Redundante dentro del grupo; menor correlación...,spi6_sequia,NaN,NaN,NaN,NaN,NaN
17,spi6_deficit_max_anual,Redundante dentro del grupo; menor correlación...,spi6_sequia,NaN,NaN,NaN,NaN,NaN
18,spi12_min_anual,Redundante dentro del grupo; menor correlación...,spi12_sequia,NaN,NaN,NaN,NaN,NaN
19,spi12_deficit_max_anual,Redundante dentro del grupo; menor correlación...,spi12_sequia,NaN,NaN,NaN,NaN,NaN
20,spi_presion_total_sequia,Redundante dentro del grupo; menor correlación...,spi_presion_total,NaN,NaN,NaN,NaN,NaN
21,spi6_presion_sequia_anual,Redundante dentro del grupo; menor correlación...,spi_presion_total,NaN,NaN,NaN,NaN,NaN
22,spi3_mean_anual,Alta correlación entre predictoras,NaN,spi6_mean_anual,0.968520,NaN,NaN,NaN
23,spi12_presion_sequia_anual,Alta correlación entre predictoras,NaN,spi12_meses_bajo_m1,0.957838,NaN,NaN,NaN
24,mínimo de la temperatura media mensual (°c),Alta correlación entre predictoras,NaN,altitud_media_m,-0.947859,NaN,NaN,NaN
25,spi3_meses_bajo_m1,Alta correlación entre predictoras,NaN,spi3_presion_sequia_anual,0.939078,NaN,NaN,NaN
26,ratio_precipitacion_evaporacion,Alta correlación entre predictoras,NaN,balance_precipitacion_evaporacion,0.938523,NaN,NaN,NaN
27,spi6_mean_anual,Alta correlación entre predictoras,NaN,spi12_mean_anual,0.909937,NaN,NaN,NaN
28,spi3_floracion,VIF mayor a 10,NaN,NaN,NaN,16.754051,0.196348,0.212392

In [91]:
X_lineal = df_fe[variables_a_usar_lineal]
y = df_fe["rendimiento"]

In [96]:
df_final_modelos = df_fe[variables_a_usar_lineal + df_fe.select_dtypes(exclude="number").columns.tolist() + ["rendimiento"]]

In [97]:
df_final_modelos.to_csv("data_fe_pca_reduction.csv")